const $=s=>document.querySelector(s);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const TASTE_KEY='asiri-music-pro.v1.taste.profile';
const state={tracks:[],busy:false,prompt:'',currentTrackId:'',currentIndex:-1};

function getBridge(){return window.AsiriMusicBridge}
function waitForBridge(){return new Promise(resolve=>{if(getBridge())return resolve(getBridge());const done=()=>{window.removeEventListener('asiri:bridge-ready',done);resolve(getBridge())};window.addEventListener('asiri:bridge-ready',done)})}
function normalizePrompt(prompt){return prompt.trim().replace(/\s+/g,' ')}
function buildQueries(prompt){const q=normalizePrompt(prompt);const lower=q.toLowerCase();const queries=[q];
  if(/قهوة|هدوء|هادئ|مساء/.test(lower))queries.push('طرب خليجي هادئ','أغاني خليجية هادئة');
  if(/سفر|طريق|سيارة|رحلة/.test(lower))queries.push('أغاني سفر خليجية','أغاني طريق عربية');
  if(/حماس|نادي|رياضة/.test(lower))queries.push('أغاني خليجية حماسية','أغاني عربية حماسية');
  if(/قديم|زمن جميل|كلاسيك/.test(lower))queries.push('كلاسيكيات خليجية','طرب سعودي قديم');
  if(/محمد عبده/.test(q))queries.push('محمد عبده طرب','محمد عبده جلسات');
  if(/طلال مداح/.test(q))queries.push('طلال مداح قديم','طلال مداح جلسات');
  if(queries.length===1)queries.push(`${q} خليجي`,`${q} عربي`);
  return [...new Set(queries)].slice(0,4)
}
function scoreTrack(track,prompt,taste){let score=track.popularity||0;const artists=(track.artists||[]).map(a=>a.name);for(const name of artists){score+=(taste?.artistScores?.[name]||taste?.artists?.[name]?.score||0)*8}const text=`${track.name} ${artists.join(' ')}`.toLowerCase();for(const word of prompt.toLowerCase().split(/\s+/)){if(word.length>2&&text.includes(word))score+=12}if(taste?.dislikedTrackIds?.includes?.(track.id)||taste?.tracks?.[track.id]?.value==='dislike')score-=1000;return score}
function loadTaste(){try{return JSON.parse(localStorage.getItem(TASTE_KEY)||'{"tracks":{},"artists":{},"events":[]}')}catch{return{tracks:{},artists:{},events:[]}}}
function saveTaste(data){localStorage.setItem(TASTE_KEY,JSON.stringify(data));window.dispatchEvent(new CustomEvent('asiri:taste-updated',{detail:data}));window.dispatchEvent(new StorageEvent('storage',{key:TASTE_KEY,newValue:JSON.stringify(data)}))}
function rateTrack(track,value){const data=loadTaste(),previous=data.tracks?.[track.id]?.value;data.tracks=data.tracks||{};data.artists=data.artists||{};data.events=data.events||[];const artists=(track.artists||[]).map(a=>a.name).filter(Boolean);const adjust=(name,type,delta)=>{const current=data.artists[name]||{likes:0,dislikes:0,score:0};if(type==='like')current.likes=Math.max(0,(current.likes||0)+delta);else current.dislikes=Math.max(0,(current.dislikes||0)+delta);current.score=(current.score||0)+(type==='like'?2:-2)*delta;data.artists[name]=current};if(previous===value){delete data.tracks[track.id];artists.forEach(name=>adjust(name,value,-1))}else{if(previous)artists.forEach(name=>adjust(name,previous,-1));artists.forEach(name=>adjust(name,value,1));data.tracks[track.id]={id:track.id,name:track.name,artist:artists.join('، '),cover:track.album?.images?.[0]?.url||'',uri:track.uri||`spotify:track:${track.id}`,value,updatedAt:Date.now()}}data.events.unshift({type:previous===value?'clear':value,trackId:track.id,at:Date.now()});data.events=data.events.slice(0,300);saveTaste(data);renderPreview()}
function ratingFor(id){return loadTaste().tracks?.[id]?.value||''}
function updateCurrentHighlight(){document.querySelectorAll('.ai-dj-track').forEach(card=>{const active=card.dataset.trackId===state.currentTrackId;card.classList.toggle('is-playing',active);const play=card.querySelector('.ai-track-play');if(play)play.textContent=active?'⏸ يعمل الآن':'▶ تشغيل'})}
async function playFrom(index){const bridge=getBridge();if(!bridge||!state.tracks[index])return;state.currentIndex=index;$('#aiDjStatus').textContent=`جارٍ تشغيل الأغنية ${index+1} من ${state.tracks.length}…`;try{await bridge.playQueue(state.tracks,{startIndex:index,source:'ai-dj'});state.currentTrackId=state.tracks[index].id;updateCurrentHighlight();$('#aiDjStatus').textContent=`يعمل الآن: ${state.tracks[index].name} — ${index+1} من ${state.tracks.length}`}catch(error){console.error(error);$('#aiDjStatus').textContent=error.message||'تعذر تشغيل الأغنية.'}}
function renderPreview(){const wrap=$('#aiDjPreview'),count=$('#aiDjCount');wrap.innerHTML='';count.textContent=state.tracks.length?`${state.tracks.length} أغنية`:'';state.tracks.forEach((track,index)=>{const item=document.createElement('article');item.className='ai-dj-track';item.dataset.trackId=track.id||'';
    const number=document.createElement('span');number.className='ai-track-number';number.textContent=String(index+1);
    const image=document.createElement('img');image.src=track.album?.images?.[0]?.url||'';image.alt='';
    const info=document.createElement('button');info.type='button';info.className='ai-track-info';const title=document.createElement('strong');title.textContent=track.name||'';const artist=document.createElement('small');artist.textContent=track.artists?.map(a=>a.name).join('، ')||'';info.append(title,artist);info.addEventListener('click',()=>playFrom(index));
    const actions=document.createElement('div');actions.className='ai-track-actions';
    const play=document.createElement('button');play.type='button';play.className='ai-track-play';play.textContent='▶ تشغيل';play.addEventListener('click',()=>playFrom(index));
    const like=document.createElement('button');like.type='button';like.className='ai-track-like';like.textContent=ratingFor(track.id)==='like'?'✓ أعجبتني':'♡ أعجبتني';like.classList.toggle('active',ratingFor(track.id)==='like');like.addEventListener('click',()=>rateTrack(track,'like'));
    const dislike=document.createElement('button');dislike.type='button';dislike.className='ai-track-dislike';dislike.textContent=ratingFor(track.id)==='dislike'?'✓ مستبعدة':'🚫 استبعاد';dislike.classList.toggle('active',ratingFor(track.id)==='dislike');dislike.addEventListener('click',()=>rateTrack(track,'dislike'));
    actions.append(play,like,dislike);item.append(number,image,info,actions);wrap.appendChild(item)});updateCurrentHighlight()}
async function generateSession(){if(state.busy)return;const bridge=getBridge();if(!bridge)return;const input=$('#aiDjPrompt'),button=$('#aiDjGenerate'),message=$('#aiDjStatus');const prompt=normalizePrompt(input.value);if(!prompt){message.textContent='اكتب نوع الجلسة التي تريدها.';return}state.busy=true;state.prompt=prompt;button.disabled=true;button.textContent='جارٍ البناء…';message.textContent='AI DJ يبحث ويجمع أفضل النتائج…';try{const queries=buildQueries(prompt),all=[];for(const query of queries){const data=await bridge.api('/search?'+new URLSearchParams({q:query,type:'track',limit:'10',offset:'0'}));all.push(...(data.tracks?.items||[]));await sleep(120)}const taste=loadTaste();const unique=[...new Map(all.filter(t=>t?.id).map(t=>[t.id,t])).values()];state.tracks=unique.map(track=>({track,score:scoreTrack(track,prompt,taste)})).sort((a,b)=>b.score-a.score).map(x=>x.track).filter(track=>taste.tracks?.[track.id]?.value!=='dislike').slice(0,30);state.currentIndex=-1;state.currentTrackId='';renderPreview();message.textContent=state.tracks.length?`تم إنشاء جلسة «${prompt}». اختر أي أغنية للبدء.`:'لم أجد نتائج كافية لهذه الجلسة.';bridge.setStorage('aiDj.lastSession',{prompt,tracks:state.tracks,createdAt:Date.now()})}catch(error){console.error(error);message.textContent=error.message||'تعذر إنشاء الجلسة الآن.'}finally{state.busy=false;button.disabled=false;button.textContent='✨ إنشاء الجلسة'}}
async function playSession(){if(!state.tracks.length){$('#aiDjStatus').textContent='أنشئ الجلسة أولًا.';return}return playFrom(0)}
async function init(){const bridge=await waitForBridge();const last=bridge.getStorage('aiDj.lastSession');if(last?.tracks?.length){state.tracks=last.tracks;state.prompt=last.prompt||'';$('#aiDjPrompt').value=state.prompt;renderPreview();$('#aiDjStatus').textContent='تم استعادة آخر جلسة. يمكنك تشغيل أي أغنية مباشرة.'}$('#aiDjGenerate').addEventListener('click',generateSession);$('#aiDjPlay').addEventListener('click',playSession);document.querySelectorAll('[data-ai-preset]').forEach(btn=>btn.addEventListener('click',()=>{$('#aiDjPrompt').value=btn.dataset.aiPreset;generateSession()}));window.addEventListener('asiri:player-state',event=>{const track=event.detail?.track;if(!track)return;state.currentTrackId=track.id||'';state.currentIndex=state.tracks.findIndex(item=>item.id===track.id);updateCurrentHighlight();if(state.currentIndex>=0)$('#aiDjStatus').textContent=`يعمل الآن: ${track.name} — ${state.currentIndex+1} من ${state.tracks.length}`})}
init().catch(error=>console.error('[AI DJ isolated]',error));