const CLIENT_ID='3ac122f971744e508bfd33ad0637d421';
const SCOPES=['user-read-private','user-read-email','streaming','user-read-playback-state','user-modify-playback-state','user-library-read','user-library-modify','playlist-read-private','playlist-modify-private','playlist-modify-public'];
const NS='asiri-music-pro.v1.';
const $=s=>document.querySelector(s);
const get=k=>{try{return JSON.parse(localStorage.getItem(NS+k)||'null')?.value??null}catch{return null}};
const set=(k,v)=>localStorage.setItem(NS+k,JSON.stringify({envelopeVersion:1,savedAt:Date.now(),value:v}));
const remove=k=>localStorage.removeItem(NS+k);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
let sdkPlayer=null,deviceId=null,searchQueue=[],currentQueueIndex=-1,transitionPromise=null,playerConnectPromise=null;
function base64url(input){return btoa(String.fromCharCode(...new Uint8Array(input))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function sha256(text){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))}
function randomString(length=64){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',values=crypto.getRandomValues(new Uint8Array(length));return Array.from(values,v=>chars[v%chars.length]).join('')}
async function login(){const verifier=randomString(),challenge=base64url(await sha256(verifier));set('spotify.codeVerifier',verifier);const redirectUri=new URL('callback.html',location.href).href;location.href='https://accounts.spotify.com/authorize?'+new URLSearchParams({client_id:CLIENT_ID,response_type:'code',redirect_uri:redirectUri,scope:SCOPES.join(' '),code_challenge_method:'S256',code_challenge:challenge,show_dialog:'true'})}
async function refresh(){const rt=get('spotify.refreshToken');if(!rt)return null;const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT_ID,grant_type:'refresh_token',refresh_token:rt})});if(!r.ok)return null;const p=await r.json();set('spotify.accessToken',p.access_token);set('spotify.expiresAt',Date.now()+p.expires_in*1000-60000);if(p.refresh_token)set('spotify.refreshToken',p.refresh_token);return p.access_token}
async function token(){const t=get('spotify.accessToken'),e=Number(get('spotify.expiresAt')||0);return t&&Date.now()<e?t:refresh()}
async function api(path,options={}){const t=await token();if(!t)throw new Error('AUTH_REQUIRED');const r=await fetch('https://api.spotify.com/v1'+path,{...options,headers:{Authorization:'Bearer '+t,...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});if(r.status===401){remove('spotify.accessToken');throw new Error('AUTH_REQUIRED')}if(!r.ok){let d='';try{d=(await r.json())?.error?.message||''}catch{}const error=new Error(d||'SPOTIFY_'+r.status);error.status=r.status;throw error}return r.status===204?null:r.json()}
function health(ok,text){$('#healthCard').classList.toggle('ok',ok);$('#healthCard').classList.toggle('warn',!ok);$('#healthStatus').textContent=text}
function status(text){$('#statusText').textContent=text}
function syncQueueIndex(track){if(!track||!searchQueue.length)return;const index=searchQueue.findIndex(item=>(track.uri&&item.uri===track.uri)||(track.id&&item.id===track.id));if(index>=0)currentQueueIndex=index}
async function resetPlayer(){deviceId=null;playerConnectPromise=null;if(sdkPlayer){try{sdkPlayer.disconnect()}catch{}sdkPlayer=null}await wait(150)}
async function initPlayer(force=false){if(force)await resetPlayer();if(deviceId&&sdkPlayer)return deviceId;if(playerConnectPromise)return playerConnectPromise;if(!window.Spotify?.Player)return null;playerConnectPromise=(async()=>{if(!sdkPlayer){sdkPlayer=new Spotify.Player({name:'Asiri Music Professional',getOAuthToken:async cb=>cb(await token()),volume:.75,enableMediaSession:true});sdkPlayer.addListener('ready',({device_id})=>{deviceId=device_id;health(true,'Spotify Player جاهز');status('المشغل متصل وجاهز.')});sdkPlayer.addListener('not_ready',()=>{deviceId=null;health(false,'جارٍ إعادة ربط المشغل…')});sdkPlayer.addListener('initialization_error',({message})=>health(false,message||'تعذر تهيئة المشغل'));sdkPlayer.addListener('authentication_error',()=>health(false,'يلزم تسجيل الدخول مجددًا'));sdkPlayer.addListener('account_error',()=>health(false,'التشغيل المباشر يتطلب Premium'));sdkPlayer.addListener('playback_error',({message})=>{console.error(message);health(false,'حدث خطأ في تشغيل Spotify')});sdkPlayer.addListener('player_state_changed',state=>{if(!state)return;const t=state.track_window.current_track;syncQueueIndex(t);$('#playerBar').classList.remove('hidden');$('#playerCover').src=t.album?.images?.[0]?.url||'';$('#playerTitle').textContent=t.name||'';$('#playerArtist').textContent=t.artists?.map(a=>a.name).join('، ')||'';$('#playButton').textContent=state.paused?'▶':'⏸';window.dispatchEvent(new CustomEvent('asiri:player-state',{detail:{track:t,paused:state.paused,position:state.position,duration:state.duration}}))})}const connected=await sdkPlayer.connect();if(!connected)throw new Error('تعذر ربط مشغل Spotify');for(let i=0;i<25&&!deviceId;i++)await wait(250);return deviceId})().finally(()=>{playerConnectPromise=null});return playerConnectPromise}
async function ensureDevice(force=false){let id=await initPlayer(force);if(!id){health(false,'جارٍ استعادة جهاز التشغيل…');id=await initPlayer(true)}if(!id)throw new Error('تعذر العثور على جهاز التشغيل. اضغط تشغيل مرة أخرى.');return id}
async function activateDevice(id){await api('/me/player',{method:'PUT',body:JSON.stringify({device_ids:[id],play:false})});await wait(250)}
async function playTrackOnce(track,index,forceReconnect=false){const id=await ensureDevice(forceReconnect);if(Number.isInteger(index))currentQueueIndex=index;await activateDevice(id);await api('/me/player/play?device_id='+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({uris:[track.uri||'spotify:track:'+track.id],position_ms:0})})}
async function playTrack(track,index){try{await playTrackOnce(track,index,false)}catch(error){const recoverable=error.status===404||/device not found|no active device|جهاز/i.test(error.message||'');if(!recoverable)throw error;health(false,'فُقد اتصال المشغل؛ جارٍ استعادته…');status('جارٍ إعادة ربط Spotify تلقائيًا…');await resetPlayer();await wait(400);await playTrackOnce(track,index,true)}health(true,'Spotify Player جاهز');status(`يعمل الآن: ${track.name} — ${currentQueueIndex+1} من ${searchQueue.length||1}`)}
function runTransition(task){if(transitionPromise)return transitionPromise;transitionPromise=Promise.resolve().then(task).catch(error=>{console.error(error);status(error.message||'تعذر الانتقال');health(false,error.message||'تعذر التشغيل')}).finally(()=>{transitionPromise=null});return transitionPromise}
function play(track,index){status('جارٍ تشغيل الأغنية…');return runTransition(()=>playTrack(track,index))}
function moveQueue(direction){if(!searchQueue.length){status('ابحث أولًا لتكوين قائمة تشغيل.');return}const base=currentQueueIndex>=0?currentQueueIndex:0;const next=(base+direction+searchQueue.length)%searchQueue.length;const track=searchQueue[next];status(direction>0?'جارٍ الانتقال إلى الأغنية التالية…':'جارٍ الرجوع إلى الأغنية السابقة…');runTransition(()=>playTrack(track,next))}
function replaceQueue(tracks,{startIndex=0,source='smart'}={}){const clean=[...new Map((tracks||[]).filter(t=>t?.id).map(t=>[t.id,t])).values()];if(!clean.length)throw new Error('لا توجد أغنيات صالحة للجلسة');searchQueue=clean;currentQueueIndex=Math.min(Math.max(startIndex,0),clean.length-1);window.dispatchEvent(new CustomEvent('asiri:queue-changed',{detail:{tracks:[...clean],source,currentIndex:currentQueueIndex}}));return [...clean]}
async function playQueue(tracks,{startIndex=0,source='smart'}={}){const queue=replaceQueue(tracks,{startIndex,source});status(`جارٍ تشغيل جلسة من ${queue.length} أغنية…`);await runTransition(()=>playTrack(queue[currentQueueIndex],currentQueueIndex));return queue}
function render(track,index){const fragment=$('#trackTemplate').content.cloneNode(true);const card=fragment.querySelector('.track');card.dataset.trackId=track.id||'';fragment.querySelector('.cover').src=track.album?.images?.[0]?.url||'';fragment.querySelector('.name').textContent=track.name||'';fragment.querySelector('.artist').textContent=track.artists?.map(a=>a.name).join('، ')||'';fragment.querySelector('.album').textContent=track.album?.name||'';fragment.querySelector('.open').href=track.external_urls?.spotify||'';fragment.querySelector('.play').addEventListener('click',event=>{event.preventDefault();play(track,index)});queueMicrotask(()=>window.dispatchEvent(new CustomEvent('asiri:track-rendered',{detail:{card,track}})));return fragment}
async function load(){health(true,'تم تحميل النواة الاحترافية');if(!get('spotify.accessToken')&&!get('spotify.refreshToken')){health(false,'بانتظار تسجيل الدخول');return}try{const me=await api('/me');$('#profileName').textContent=me.display_name||me.id;$('#profilePlan').textContent=me.product==='premium'?'Spotify Premium':'Spotify متصل';$('#profileCard').classList.remove('hidden');$('#loginButton').classList.add('hidden');health(true,'النظام متصل ومستقر');status('تم الاتصال. جارٍ تجهيز المشغل…');await initPlayer()}catch(e){console.error(e);health(false,'يلزم تسجيل الدخول مجددًا')}}
$('#loginButton').addEventListener('click',login);
$('#searchForm').addEventListener('submit',async e=>{e.preventDefault();const q=$('#searchInput').value.trim();if(!q)return;$('#results').innerHTML='';status('جارٍ البحث…');try{const data=await api('/search?'+new URLSearchParams({q,type:'track',limit:'10',offset:'0'}));searchQueue=data.tracks?.items||[];currentQueueIndex=-1;searchQueue.forEach((t,index)=>$('#results').appendChild(render(t,index)));$('#resultCount').textContent=searchQueue.length+' نتيجة';status(searchQueue.length?'شغّل أي أغنية ثم استخدم السابق والتالي.':'لا توجد نتائج.')}catch(err){console.error(err);status(err.message==='AUTH_REQUIRED'?'سجّل الدخول أولًا.':err.message)}});
$('#playButton').addEventListener('click',event=>{event.preventDefault();if(sdkPlayer&&deviceId)sdkPlayer.togglePlay();else if(searchQueue[currentQueueIndex])play(searchQueue[currentQueueIndex],currentQueueIndex)});
$('#prevButton').addEventListener('click',event=>{event.preventDefault();event.stopPropagation();moveQueue(-1)});
$('#nextButton').addEventListener('click',event=>{event.preventDefault();event.stopPropagation();moveQueue(1)});
window.onSpotifyWebPlaybackSDKReady=()=>initPlayer().catch(console.error);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&get('spotify.refreshToken')&&!deviceId)initPlayer(true).catch(console.error)});
window.addEventListener('pageshow',event=>{if(event.persisted||!deviceId)initPlayer(true).catch(console.error)});
window.addEventListener('online',()=>{if(!deviceId)initPlayer(true).catch(console.error)});
window.addEventListener('error',e=>{console.error(e.error||e.message);health(false,'تم عزل خطأ دون إيقاف التطبيق')});
window.addEventListener('unhandledrejection',e=>{console.error(e.reason);health(false,'تم احتواء خطأ غير متوقع')});
window.AsiriMusicBridge={api,playQueue,replaceQueue,getQueue:()=>[...searchQueue],getCurrentIndex:()=>currentQueueIndex,setStatus:status,getStorage:get,setStorage:set,reconnectPlayer:()=>initPlayer(true)};
window.dispatchEvent(new CustomEvent('asiri:bridge-ready'));
load();