const CLIENT_ID='3ac122f971744e508bfd33ad0637d421';
const SCOPES=['user-read-private','user-read-email','streaming','user-read-playback-state','user-modify-playback-state','user-library-read','user-library-modify','playlist-read-private','playlist-modify-private','playlist-modify-public'];
const NS='asiri-music-pro.v1.';
const $=s=>document.querySelector(s);
const get=k=>{try{return JSON.parse(localStorage.getItem(NS+k)||'null')?.value??null}catch{return null}};
const set=(k,v)=>localStorage.setItem(NS+k,JSON.stringify({envelopeVersion:1,savedAt:Date.now(),value:v}));
const remove=k=>localStorage.removeItem(NS+k);
let sdkPlayer=null,deviceId=null;
function base64url(input){return btoa(String.fromCharCode(...new Uint8Array(input))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function sha256(text){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))}
function randomString(length=64){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',values=crypto.getRandomValues(new Uint8Array(length));return Array.from(values,v=>chars[v%chars.length]).join('')}
async function login(){const verifier=randomString(),challenge=base64url(await sha256(verifier));set('spotify.codeVerifier',verifier);const redirectUri=new URL('callback.html',location.href).href;location.href='https://accounts.spotify.com/authorize?'+new URLSearchParams({client_id:CLIENT_ID,response_type:'code',redirect_uri:redirectUri,scope:SCOPES.join(' '),code_challenge_method:'S256',code_challenge:challenge,show_dialog:'true'})}
async function refresh(){const rt=get('spotify.refreshToken');if(!rt)return null;const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT_ID,grant_type:'refresh_token',refresh_token:rt})});if(!r.ok)return null;const p=await r.json();set('spotify.accessToken',p.access_token);set('spotify.expiresAt',Date.now()+p.expires_in*1000-60000);if(p.refresh_token)set('spotify.refreshToken',p.refresh_token);return p.access_token}
async function token(){const t=get('spotify.accessToken'),e=Number(get('spotify.expiresAt')||0);return t&&Date.now()<e?t:refresh()}
async function api(path,options={}){const t=await token();if(!t)throw new Error('AUTH_REQUIRED');const r=await fetch('https://api.spotify.com/v1'+path,{...options,headers:{Authorization:'Bearer '+t,...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});if(r.status===401){remove('spotify.accessToken');throw new Error('AUTH_REQUIRED')}if(!r.ok){let d='';try{d=(await r.json())?.error?.message||''}catch{}throw new Error(d||'SPOTIFY_'+r.status)}return r.status===204?null:r.json()}
function health(ok,text){$('#healthCard').classList.toggle('ok',ok);$('#healthCard').classList.toggle('warn',!ok);$('#healthStatus').textContent=text}
function status(text){$('#statusText').textContent=text}
async function initPlayer(){if(sdkPlayer||!window.Spotify?.Player)return;sdkPlayer=new Spotify.Player({name:'Asiri Music Professional',getOAuthToken:async cb=>cb(await token()),volume:.75,enableMediaSession:true});sdkPlayer.addListener('ready',({device_id})=>{deviceId=device_id;health(true,'Spotify Player جاهز')});sdkPlayer.addListener('not_ready',()=>{deviceId=null;health(false,'المشغل غير متصل')});sdkPlayer.addListener('player_state_changed',state=>{if(!state)return;const t=state.track_window.current_track;$('#playerBar').classList.remove('hidden');$('#playerCover').src=t.album?.images?.[0]?.url||'';$('#playerTitle').textContent=t.name||'';$('#playerArtist').textContent=t.artists?.map(a=>a.name).join('، ')||'';$('#playButton').textContent=state.paused?'▶':'⏸';window.dispatchEvent(new CustomEvent('asiri:player-state',{detail:{track:t,paused:state.paused,position:state.position,duration:state.duration}}))});sdkPlayer.addListener('account_error',()=>health(false,'التشغيل المباشر يتطلب Premium'));await sdkPlayer.connect()}
async function play(track){status('جارٍ تجهيز المشغل…');await initPlayer();for(let i=0;i<12&&!deviceId;i++)await new Promise(r=>setTimeout(r,400));if(!deviceId)throw new Error('المشغل غير جاهز');await api('/me/player',{method:'PUT',body:JSON.stringify({device_ids:[deviceId],play:false})});await api('/me/player/play?device_id='+encodeURIComponent(deviceId),{method:'PUT',body:JSON.stringify({uris:[track.uri||'spotify:track:'+track.id]})});status('بدأ التشغيل داخل النسخة الاحترافية ✓')}
function render(track){const fragment=$('#trackTemplate').content.cloneNode(true);const card=fragment.querySelector('.track');card.dataset.trackId=track.id||'';fragment.querySelector('.cover').src=track.album?.images?.[0]?.url||'';fragment.querySelector('.name').textContent=track.name||'';fragment.querySelector('.artist').textContent=track.artists?.map(a=>a.name).join('، ')||'';fragment.querySelector('.album').textContent=track.album?.name||'';fragment.querySelector('.open').href=track.external_urls?.spotify||'';fragment.querySelector('.play').onclick=()=>play(track).catch(e=>{console.error(e);status(e.message||'تعذر التشغيل')});queueMicrotask(()=>window.dispatchEvent(new CustomEvent('asiri:track-rendered',{detail:{card,track}})));return fragment}
async function load(){health(true,'تم تحميل النواة الاحترافية');if(!get('spotify.accessToken')&&!get('spotify.refreshToken')){health(false,'بانتظار تسجيل الدخول');return}try{const me=await api('/me');$('#profileName').textContent=me.display_name||me.id;$('#profilePlan').textContent=me.product==='premium'?'Spotify Premium':'Spotify متصل';$('#profileCard').classList.remove('hidden');$('#loginButton').classList.add('hidden');health(true,'النظام متصل ومستقر');status('تم الاتصال. يمكنك البحث والتشغيل.');await initPlayer()}catch(e){console.error(e);health(false,'يلزم تسجيل الدخول مجددًا')}}
$('#loginButton').onclick=login;
$('#searchForm').onsubmit=async e=>{e.preventDefault();const q=$('#searchInput').value.trim();if(!q)return;$('#results').innerHTML='';status('جارٍ البحث…');try{const data=await api('/search?'+new URLSearchParams({q,type:'track',limit:'10',offset:'0'}));const items=data.tracks?.items||[];items.forEach(t=>$('#results').appendChild(render(t)));$('#resultCount').textContent=items.length+' نتيجة';status(items.length?'اختر أغنية للتشغيل والتقييم.':'لا توجد نتائج.')}catch(err){console.error(err);status(err.message==='AUTH_REQUIRED'?'سجّل الدخول أولًا.':err.message)}};
$('#playButton').onclick=()=>sdkPlayer?.togglePlay();$('#prevButton').onclick=()=>sdkPlayer?.previousTrack();$('#nextButton').onclick=()=>sdkPlayer?.nextTrack();
window.onSpotifyWebPlaybackSDKReady=()=>initPlayer().catch(console.error);
window.addEventListener('error',e=>{console.error(e.error||e.message);health(false,'تم عزل خطأ دون إيقاف التطبيق')});
window.addEventListener('unhandledrejection',e=>{console.error(e.reason);health(false,'تم احتواء خطأ غير متوقع')});
load();