const NS='asiri-music-pro.v1.';
const $=s=>document.querySelector(s);
const read=k=>{try{return JSON.parse(localStorage.getItem(NS+k)||'null')?.value??null}catch{return null}};
const write=(k,v)=>localStorage.setItem(NS+k,JSON.stringify({envelopeVersion:1,savedAt:Date.now(),value:v}));
const state={enabled:Boolean(read('carMode.enabled')),deviceId:read('carMode.deviceId')||'',devices:[],poller:null};

function waitForBridge(){return new Promise(resolve=>{if(window.AsiriMusicBridge)return resolve(window.AsiriMusicBridge);const done=()=>{window.removeEventListener('asiri:bridge-ready',done);resolve(window.AsiriMusicBridge)};window.addEventListener('asiri:bridge-ready',done)})}
function isWebDevice(device){return /Asiri Music Professional/i.test(device?.name||'')}
function preferredDevice(devices){return devices.find(d=>d.id===state.deviceId&&!isWebDevice(d))||devices.find(d=>d.is_active&&!isWebDevice(d))||devices.find(d=>/smartphone|computer|speaker|tv|avr/i.test(d.type||'')&&!isWebDevice(d))||devices.find(d=>!isWebDevice(d))||null}
function updateStatus(text,ok=true){const el=$('#carStatus');if(el){el.textContent=text;el.dataset.ok=ok?'1':'0'}}
function renderDevices(){const select=$('#carDevice');if(!select)return;select.innerHTML='';const usable=state.devices.filter(d=>!isWebDevice(d));if(!usable.length){select.innerHTML='<option value="">لا يوجد جهاز Spotify خارجي</option>';return}for(const d of usable){const option=document.createElement('option');option.value=d.id;option.textContent=`${d.name}${d.is_active?' • نشط':''} (${d.type||'Device'})`;select.appendChild(option)}const preferred=preferredDevice(usable);if(preferred){select.value=preferred.id;state.deviceId=preferred.id;write('carMode.deviceId',preferred.id)}}
async function refreshDevices(bridge){try{const data=await bridge.api('/me/player/devices');state.devices=data.devices||[];renderDevices();const selected=preferredDevice(state.devices);updateStatus(selected?`الجهاز المختار: ${selected.name}`:'افتح Spotify وشغّل أي أغنية مرة واحدة ليظهر جهاز السيارة أو الآيفون.',Boolean(selected));return selected}catch(error){console.error('[Car Connect devices]',error);updateStatus(error.message||'تعذر قراءة أجهزة Spotify.',false);return null}}
async function activateDevice(bridge,deviceId,play=false){await bridge.api('/me/player',{method:'PUT',body:JSON.stringify({device_ids:[deviceId],play})});await new Promise(r=>setTimeout(r,300))}
async function ensureExternalDevice(bridge){await refreshDevices(bridge);let device=preferredDevice(state.devices);if(!device){window.location.href='spotify://';throw new Error('افتح تطبيق Spotify وشغّل أي أغنية، ثم ارجع واضغط تحديث الأجهزة.')}state.deviceId=device.id;write('carMode.deviceId',device.id);await activateDevice(bridge,device.id,false);return device}
function showTrack(track,paused=false){if(!track)return;const bar=$('#playerBar');bar?.classList.remove('hidden');if($('#playerCover'))$('#playerCover').src=track.album?.images?.[0]?.url||'';if($('#playerTitle'))$('#playerTitle').textContent=track.name||'';if($('#playerArtist'))$('#playerArtist').textContent=(track.artists||[]).map(a=>a.name).join('، ');if($('#playButton'))$('#playButton').textContent=paused?'▶':'⏸'}
async function playOnCar(bridge,tracks,{startIndex=0,source='car'}={}){const queue=bridge.replaceQueue(tracks,{startIndex,source});const device=await ensureExternalDevice(bridge);const uris=queue.map(t=>t.uri||`spotify:track:${t.id}`).filter(Boolean).slice(0,100);if(!uris.length)throw new Error('لا توجد أغنيات قابلة للتشغيل.');showTrack(queue[startIndex],false);updateStatus(`جارٍ التشغيل على ${device.name}…`);await bridge.api('/me/player/play?device_id='+encodeURIComponent(device.id),{method:'PUT',body:JSON.stringify({uris,offset:{position:startIndex},position_ms:0})});bridge.setStatus(`التشغيل عبر Spotify Connect على ${device.name}. أزرار السيارة جاهزة.`);updateStatus(`متصل بـ ${device.name} • أزرار السيارة تعمل عبر Spotify`,true);startPolling(bridge);return queue}
async function playerCommand(bridge,command){const device=await ensureExternalDevice(bridge);if(command==='toggle'){const playback=await bridge.api('/me/player');if(playback?.is_playing)await bridge.api('/me/player/pause?device_id='+encodeURIComponent(device.id),{method:'PUT'});else await bridge.api('/me/player/play?device_id='+encodeURIComponent(device.id),{method:'PUT'});return}await bridge.api(`/me/player/${command}?device_id=${encodeURIComponent(device.id)}`,{method:'POST'})}
async function pollPlayback(bridge){if(!state.enabled)return;try{const playback=await bridge.api('/me/player');if(playback?.item){showTrack(playback.item,!playback.is_playing);const index=bridge.getQueue().findIndex(t=>t.id===playback.item.id);window.dispatchEvent(new CustomEvent('asiri:player-state',{detail:{track:playback.item,paused:!playback.is_playing,position:playback.progress_ms||0,duration:playback.item.duration_ms||0,index}}))}}catch(error){console.warn('[Car Connect poll]',error)}}
function startPolling(bridge){clearInterval(state.poller);pollPlayback(bridge);state.poller=setInterval(()=>pollPlayback(bridge),3000)}
function buildUI(bridge){const card=document.createElement('section');card.className='card car-connect-card';card.innerHTML=`<div class="section-head"><div><span class="eyebrow">SPOTIFY CONNECT</span><h2>وضع السيارة</h2></div><label class="car-switch"><input id="carModeToggle" type="checkbox"><span></span></label></div><p class="muted">يشغّل الموسيقى داخل تطبيق Spotify أو جهاز السيارة، حتى تعمل أزرار المقود والسابق والتالي.</p><div class="car-controls"><select id="carDevice"></select><button id="carRefresh" type="button">تحديث الأجهزة</button><a id="openSpotify" href="spotify://">فتح Spotify</a></div><p id="carStatus" class="muted">جارٍ فحص أجهزة Spotify…</p>`;const anchor=$('#aiDjCard')||document.querySelector('main .card:nth-of-type(3)');anchor?.parentNode.insertBefore(card,anchor);$('#carModeToggle').checked=state.enabled;$('#carModeToggle').addEventListener('change',async event=>{state.enabled=event.target.checked;write('carMode.enabled',state.enabled);if(state.enabled){updateStatus('جارٍ تفعيل وضع السيارة…');await refreshDevices(bridge);startPolling(bridge)}else{clearInterval(state.poller);updateStatus('وضع السيارة متوقف. سيستخدم التطبيق مشغل الويب.')}});$('#carRefresh').addEventListener('click',()=>refreshDevices(bridge));$('#carDevice').addEventListener('change',event=>{state.deviceId=event.target.value;write('carMode.deviceId',state.deviceId);const d=state.devices.find(x=>x.id===state.deviceId);updateStatus(d?`تم اختيار ${d.name}`:'اختر جهازًا.')} );refreshDevices(bridge);if(state.enabled)startPolling(bridge)}
function interceptPlayerButtons(bridge){const commands=[['#prevButton','previous'],['#playButton','toggle'],['#nextButton','next']];for(const [selector,command] of commands){$(selector)?.addEventListener('click',async event=>{if(!state.enabled)return;event.preventDefault();event.stopImmediatePropagation();try{await playerCommand(bridge,command);setTimeout(()=>pollPlayback(bridge),400)}catch(error){console.error(error);updateStatus(error.message||'تعذر تنفيذ أمر السيارة.',false)}},true)}}
async function init(){const bridge=await waitForBridge();const originalPlayQueue=bridge.playQueue.bind(bridge);bridge.playQueue=async(tracks,options={})=>state.enabled?playOnCar(bridge,tracks,options):originalPlayQueue(tracks,options);bridge.isCarMode=()=>state.enabled;bridge.refreshCarDevices=()=>refreshDevices(bridge);buildUI(bridge);interceptPlayerButtons(bridge);window.addEventListener('pageshow',()=>{if(state.enabled)refreshDevices(bridge)});document.addEventListener('visibilitychange',()=>{if(state.enabled&&document.visibilityState==='visible')refreshDevices(bridge)})}
init().catch(error=>console.error('[Car Connect isolated]',error));