const KEY='asiri-music-pro.v1.taste.profile';
const $=s=>document.querySelector(s);

function load(){
  try{return JSON.parse(localStorage.getItem(KEY)||'{"tracks":{},"artists":{},"events":[]}')}
  catch{return{tracks:{},artists:{},events:[]}}
}
function save(data){localStorage.setItem(KEY,JSON.stringify(data));renderDashboard();window.dispatchEvent(new CustomEvent('asiri:taste-updated',{detail:data}))}
function artistNames(track){return (track?.artists||[]).map(a=>a.name).filter(Boolean)}
function adjustArtist(data,name,type,delta){const current=data.artists[name]||{likes:0,dislikes:0,score:0};if(type==='like')current.likes=Math.max(0,current.likes+delta);else current.dislikes=Math.max(0,current.dislikes+delta);current.score+=(type==='like'?2:-2)*delta;data.artists[name]=current}
function rate(track,value){if(!track?.id)return;const data=load(),previous=data.tracks[track.id]?.value;const artists=artistNames(track);if(previous===value){delete data.tracks[track.id];artists.forEach(name=>adjustArtist(data,name,value,-1));data.events.unshift({type:'clear',trackId:track.id,at:Date.now()})}else{if(previous)artists.forEach(name=>adjustArtist(data,name,previous,-1));artists.forEach(name=>adjustArtist(data,name,value,1));data.tracks[track.id]={id:track.id,name:track.name,artist:artists.join('، '),cover:track.album?.images?.[0]?.url||'',uri:track.uri||`spotify:track:${track.id}`,value,updatedAt:Date.now()};data.events.unshift({type:value,trackId:track.id,artist:artists.join('، '),at:Date.now()})}data.events=data.events.slice(0,300);save(data)}
function getRating(id){return load().tracks[id]?.value||''}
function syncButtons(card,track){const value=getRating(track.id),like=card.querySelector('.taste-like'),dislike=card.querySelector('.taste-dislike');like?.classList.toggle('active',value==='like');dislike?.classList.toggle('active',value==='dislike');if(like)like.textContent=value==='like'?'✓ أعجبتني':'👍 أعجبتني';if(dislike)dislike.textContent=value==='dislike'?'✓ مستبعدة':'🚫 لا تناسبني'}
function enhanceTrack(card,track){if(!card||card.dataset.tasteReady)return;card.dataset.tasteReady='1';const wrap=document.createElement('div');wrap.className='taste-actions';wrap.innerHTML='<button class="taste-like" type="button">👍 أعجبتني</button><button class="taste-dislike" type="button">🚫 لا تناسبني</button>';card.appendChild(wrap);wrap.querySelector('.taste-like').onclick=()=>{rate(track,'like');syncButtons(card,track)};wrap.querySelector('.taste-dislike').onclick=()=>{rate(track,'dislike');syncButtons(card,track)};syncButtons(card,track)}
function renderDashboard(){const root=$('#tasteDashboard');if(!root)return;const data=load(),tracks=Object.values(data.tracks||{}),likes=tracks.filter(x=>x.value==='like'),dislikes=tracks.filter(x=>x.value==='dislike'),artists=Object.entries(data.artists||{}).filter(([,v])=>(v.score||0)!==0).sort((a,b)=>(b[1].score||0)-(a[1].score||0));$('#tasteLikes').textContent=likes.length;$('#tasteDislikes').textContent=dislikes.length;$('#tasteArtists').textContent=artists.length;const maturity=Math.min(100,Math.round((likes.length*7+dislikes.length*3+artists.length*5)));$('#tasteScore').textContent=maturity;$('#tasteTopArtists').innerHTML=artists.slice(0,5).map(([name,v],i)=>`<div><span>${i+1}</span><strong>${name}</strong><b>${v.score>0?'+':''}${v.score}</b></div>`).join('')||'<p class="muted">قيّم بعض الأغاني ليبدأ النظام بالتعلم.</p>';$('#tasteSummary').textContent=maturity>=70?'ملف ذوقك أصبح قويًا وجاهزًا للتوصيات الذكية.':maturity>=30?'يتعلم التطبيق بسرعة من اختياراتك.':'ابدأ باستخدام أعجبتني ولا تناسبني لبناء ملف ذوقك.'}
window.addEventListener('asiri:track-rendered',event=>{try{enhanceTrack(event.detail.card,event.detail.track)}catch(error){console.error('[Taste Engine isolated]',error)}});
window.addEventListener('storage',renderDashboard);
renderDashboard();
window.AsiriTasteEngine={rate,getRating};
