const CLIENT_ID='3ac122f971744e508bfd33ad0637d421';
const SCOPES=['user-read-private','user-read-email','user-library-read','user-library-modify','playlist-read-private','playlist-modify-private','playlist-modify-public','streaming','user-read-playback-state','user-modify-playback-state'];
const redirectUri=new URL('callback.html',window.location.href).href;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const authButton=$('#authButton'),logoutButton=$('#logoutButton'),profileCard=$('#profileCard'),profileImage=$('#profileImage'),profileName=$('#profileName'),profilePlan=$('#profilePlan');
const searchForm=$('#searchForm'),searchInput=$('#searchInput'),results=$('#results'),playlists=$('#playlists'),favorites=$('#favorites'),resultCount=$('#resultCount'),statusText=$('#statusText'),refreshPlaylists=$('#refreshPlaylists'),trackTemplate=$('#trackTemplate');
const recentSearches=$('#recentSearches'),clearHistory=$('#clearHistory'),playlistStat=$('#playlistStat'),searchStat=$('#searchStat'),favoriteStat=$('#favoriteStat'),favoriteCount=$('#favoriteCount'),welcomeTitle=$('#welcomeTitle');
const playerBar=$('#playerBar'),playerCover=$('#playerCover'),playerTrack=$('#playerTrack'),playerArtist=$('#playerArtist'),playerProgress=$('#playerProgress'),playerStatus=$('#playerStatus'),playPauseButton=$('#playPauseButton'),previousButton=$('#previousButton'),nextButton=$('#nextButton');
const openNowPlaying=$('#openNowPlaying'),openNowPlayingMeta=$('#openNowPlayingMeta'),nowPlaying=$('#nowPlaying'),closeNowPlaying=$('#closeNowPlaying'),nowCover=$('#nowCover'),nowTrack=$('#nowTrack'),nowArtist=$('#nowArtist'),nowSeek=$('#nowSeek'),nowPosition=$('#nowPosition'),nowDuration=$('#nowDuration'),nowPrevious=$('#nowPrevious'),nowPlayPause=$('#nowPlayPause'),nowNext=$('#nowNext'),nowSave=$('#nowSave'),nowFavoriteButton=$('#nowFavoriteButton'),nowSpotifyLink=$('#nowSpotifyLink'),nowStatus=$('#nowStatus'),nowPlayingBackdrop=$('#nowPlayingBackdrop');
let favoriteTracks=JSON.parse(localStorage.getItem('asiri_favorites')||'[]'),searchHistory=JSON.parse(localStorage.getItem('asiri_search_history')||'[]');
let spotifyPlayer=null,playerDeviceId=null,currentPaused=true,currentTrack=null,currentPosition=0,currentDuration=0,positionTimer=null;

function base64url(input){return btoa(String.fromCharCode(...new Uint8Array(input))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function sha256(text){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))}
function randomString(length=64){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',values=crypto.getRandomValues(new Uint8Array(length));return Array.from(values,v=>chars[v%chars.length]).join('')}
function storeTokens(p){localStorage.setItem('spotify_access_token',p.access_token);localStorage.setItem('spotify_expires_at',String(Date.now()+p.expires_in*1000-60000));if(p.refresh_token)localStorage.setItem('spotify_refresh_token',p.refresh_token)}
function clearTokens(){['spotify_access_token','spotify_expires_at','spotify_refresh_token','spotify_code_verifier'].forEach(k=>localStorage.removeItem(k))}
async function login(){const verifier=randomString(),challenge=base64url(await sha256(verifier));localStorage.setItem('spotify_code_verifier',verifier);const params=new URLSearchParams({client_id:CLIENT_ID,response_type:'code',redirect_uri:redirectUri,scope:SCOPES.join(' '),code_challenge_method:'S256',code_challenge:challenge,show_dialog:'true'});location.href=`https://accounts.spotify.com/authorize?${params}`}
async function refreshAccessToken(){const refreshToken=localStorage.getItem('spotify_refresh_token');if(!refreshToken)return null;const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT_ID,grant_type:'refresh_token',refresh_token:refreshToken})});if(!r.ok)return null;const p=await r.json();storeTokens(p);return p.access_token}
async function getAccessToken(){const token=localStorage.getItem('spotify_access_token'),expires=Number(localStorage.getItem('spotify_expires_at')||0);return token&&Date.now()<expires?token:refreshAccessToken()}
async function spotify(path,options={}){const token=await getAccessToken();if(!token)throw new Error('AUTH_REQUIRED');const r=await fetch(`https://api.spotify.com/v1${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});if(r.status===401){clearTokens();throw new Error('AUTH_REQUIRED')}if(!r.ok){let detail='';try{const p=await r.json();detail=p?.error?.message||p?.error||''}catch{}throw new Error(`SPOTIFY_${r.status}${detail?`: ${detail}`:''}`)}return r.status===204?null:r.json()}
function formatTime(ms){if(!Number.isFinite(ms)||ms<0)return'0:00';const total=Math.floor(ms/1000),m=Math.floor(total/60),s=String(total%60).padStart(2,'0');return`${m}:${s}`}

function openView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));if(name==='library')renderFavorites();scrollTo({top:0,behavior:'smooth'})}
$$('.tab').forEach(t=>t.addEventListener('click',()=>openView(t.dataset.view)));$$('[data-open-search]').forEach(b=>b.addEventListener('click',()=>openView('search')));
function persistFavorites(){localStorage.setItem('asiri_favorites',JSON.stringify(favoriteTracks));updateStats();renderFavorites();syncNowFavorite()}
function toggleFavorite(track){if(!track?.id)return;const i=favoriteTracks.findIndex(x=>x.id===track.id);if(i>=0)favoriteTracks.splice(i,1);else favoriteTracks.unshift({id:track.id,name:track.name,uri:track.uri,artists:track.artists,album:track.album,external_urls:track.external_urls});persistFavorites()}
function isFavorite(id){return favoriteTracks.some(t=>t.id===id)}
function addHistory(q){searchHistory=[q,...searchHistory.filter(x=>x!==q)].slice(0,8);localStorage.setItem('asiri_search_history',JSON.stringify(searchHistory));renderHistory();updateStats()}
function renderHistory(){recentSearches.innerHTML='';if(!searchHistory.length){recentSearches.innerHTML='<span class="muted">لا يوجد سجل بعد.</span>';return}searchHistory.forEach(q=>{const b=document.createElement('button');b.className='chip';b.textContent=q;b.onclick=()=>runQuickSearch(q);recentSearches.appendChild(b)})}
function updateStats(){searchStat.textContent=searchHistory.length;favoriteStat.textContent=favoriteTracks.length;favoriteCount.textContent=favoriteTracks.length?`${favoriteTracks.length} أغنية`:''}

async function loadProfile(){try{const me=await spotify('/me');profileName.textContent=me.display_name||me.id;profilePlan.textContent=me.product==='premium'?'Spotify Premium':'Spotify متصل';profileImage.src=me.images?.[0]?.url||'';profileCard.classList.remove('hidden');authButton.classList.add('hidden');welcomeTitle.textContent=`مرحبًا ${String(me.display_name||'أحمد').split(' ')[0]}`;statusText.textContent='تم الربط بنجاح. ابحث واختر «تشغيل هنا».';await loadPlaylists();initPlayer()}catch{profileCard.classList.add('hidden');authButton.classList.remove('hidden')}}

function syncNowFavorite(){const active=isFavorite(currentTrack?.id);nowSave.textContent=active?'♥ ضمن مفضلتي':'♡ مفضلة Asiri';nowFavoriteButton.textContent=active?'♥':'♡';nowSave.classList.toggle('active',active);nowFavoriteButton.classList.toggle('active',active)}
function renderPlayer(){const image=currentTrack?.album?.images?.[0]?.url||'';const artists=currentTrack?.artists?.map(a=>a.name).join('، ')||'Asiri Music Player';const name=currentTrack?.name||'اختر أغنية';const ratio=currentDuration?Math.min(1,currentPosition/currentDuration):0;playerBar.classList.remove('hidden');playerCover.src=image;playerTrack.textContent=name;playerArtist.textContent=artists;playerProgress.style.width=`${ratio*100}%`;playPauseButton.textContent=currentPaused?'▶':'⏸';playerStatus.textContent=currentPaused?'متوقف مؤقتًا':'يعمل الآن';nowCover.src=image;nowTrack.textContent=name;nowArtist.textContent=artists;nowSeek.value=String(Math.round(ratio*1000));nowPosition.textContent=formatTime(currentPosition);nowDuration.textContent=formatTime(currentDuration);nowPlayPause.textContent=currentPaused?'▶':'⏸';nowStatus.textContent=currentPaused?'متوقف مؤقتًا':'يعمل الآن';nowSpotifyLink.href=currentTrack?.external_urls?.spotify||`https://open.spotify.com/track/${currentTrack?.id||''}`;nowPlayingBackdrop.style.backgroundImage=image?`linear-gradient(180deg,rgba(5,8,6,.18),rgba(5,8,6,.96)),url("${image}")`:'';syncNowFavorite()}
function updatePlayerState(state){if(!state)return;const t=state.track_window.current_track;currentTrack={id:t?.id,name:t?.name,uri:t?.uri,artists:t?.artists,album:t?.album,external_urls:t?.external_urls};currentPaused=state.paused;currentPosition=state.position||0;currentDuration=state.duration||0;renderPlayer();clearInterval(positionTimer);if(!currentPaused){positionTimer=setInterval(()=>{currentPosition=Math.min(currentDuration,currentPosition+1000);renderPlayer()},1000)}}
async function initPlayer(){if(spotifyPlayer||!window.Spotify)return;const token=await getAccessToken();if(!token)return;spotifyPlayer=new Spotify.Player({name:'Asiri Music Player',getOAuthToken:async cb=>cb(await getAccessToken()),volume:.75,enableMediaSession:true});spotifyPlayer.addListener('ready',({device_id})=>{playerDeviceId=device_id;playerBar.classList.remove('hidden');playerStatus.textContent='المشغل جاهز';nowStatus.textContent='المشغل جاهز'});spotifyPlayer.addListener('not_ready',()=>{playerDeviceId=null;playerStatus.textContent='المشغل غير متصل'});spotifyPlayer.addListener('player_state_changed',updatePlayerState);spotifyPlayer.addListener('initialization_error',({message})=>{playerStatus.textContent='المتصفح لا يدعم التشغيل المباشر';console.error(message)});spotifyPlayer.addListener('authentication_error',({message})=>{playerStatus.textContent='يلزم تسجيل الدخول مجددًا';console.error(message)});spotifyPlayer.addListener('account_error',({message})=>{playerStatus.textContent='التشغيل المباشر يتطلب Premium';console.error(message)});spotifyPlayer.addListener('playback_error',({message})=>{playerStatus.textContent='تعذر تشغيل الأغنية';console.error(message)});await spotifyPlayer.connect()}
window.onSpotifyWebPlaybackSDKReady=()=>initPlayer();
async function playTrack(track){try{if(!playerDeviceId){await initPlayer();await new Promise(r=>setTimeout(r,900))}if(!playerDeviceId)throw new Error('PLAYER_NOT_READY');await spotify('/me/player',{method:'PUT',body:JSON.stringify({device_ids:[playerDeviceId],play:false})});await spotify(`/me/player/play?device_id=${encodeURIComponent(playerDeviceId)}`,{method:'PUT',body:JSON.stringify({uris:[track.uri||`spotify:track:${track.id}`]})});currentTrack=track;currentPaused=false;currentPosition=0;currentDuration=track.duration_ms||0;renderPlayer();openNowPlayingScreen()}catch(error){console.error(error);playerBar.classList.remove('hidden');playerStatus.textContent=error.message==='PLAYER_NOT_READY'?'اضغط تسجيل الدخول مجددًا لمنح صلاحية التشغيل':'تعذر التشغيل؛ افتحها في Spotify'}}
function openNowPlayingScreen(){if(!currentTrack)return;nowPlaying.classList.remove('hidden');document.body.classList.add('player-opened');renderPlayer()}
function closeNowPlayingScreen(){nowPlaying.classList.add('hidden');document.body.classList.remove('player-opened')}
async function togglePlayback(){if(!spotifyPlayer)return;await spotifyPlayer.activateElement();await spotifyPlayer.togglePlay()}

function createTrackCard(track){const node=trackTemplate.content.cloneNode(true),fav=node.querySelector('.favorite-track');node.querySelector('.track-cover').src=track.album?.images?.[0]?.url||'';node.querySelector('.track-name').textContent=track.name||'بدون اسم';node.querySelector('.track-artist').textContent=track.artists?.map(a=>a.name).join('، ')||'';node.querySelector('.track-album').textContent=track.album?.name||'';node.querySelector('.open-spotify').href=track.external_urls?.spotify||`https://open.spotify.com/track/${track.id}`;node.querySelector('.play-track').onclick=()=>playTrack(track);fav.classList.toggle('active',isFavorite(track.id));fav.textContent=isFavorite(track.id)?'♥ ضمن مفضلتي':'♡ مفضلة Asiri';fav.onclick=()=>{toggleFavorite(track);fav.classList.toggle('active',isFavorite(track.id));fav.textContent=isFavorite(track.id)?'♥ ضمن مفضلتي':'♡ مفضلة Asiri'};node.querySelector('.save-track').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await spotify('/me/library',{method:'PUT',body:JSON.stringify({uris:[track.uri||`spotify:track:${track.id}`]})});b.textContent='تم الحفظ ✓'}catch{b.textContent='تعذر الحفظ'}finally{b.disabled=false}};return node}
function renderTracks(items=[]){results.innerHTML='';resultCount.textContent=items.length?`${items.length} نتيجة`:'';items.forEach(t=>results.appendChild(createTrackCard(t)))}
function renderFavorites(){favorites.innerHTML='';updateStats();if(!favoriteTracks.length){favorites.innerHTML='<p class="muted">أضف الأغاني من نتائج البحث لتظهر هنا.</p>';return}favoriteTracks.forEach(t=>favorites.appendChild(createTrackCard(t)))}
async function searchTracks(query){statusText.textContent='جارٍ البحث...';results.innerHTML='';resultCount.textContent='';try{const params=new URLSearchParams({q:query,type:'track',limit:'10',offset:'0'}),data=await spotify(`/search?${params}`),items=data.tracks?.items||[];renderTracks(items);addHistory(query);statusText.textContent=items.length?'اضغط «تشغيل هنا» للاستماع داخل Asiri Music.':'لم يتم العثور على نتائج.'}catch(error){statusText.textContent=error.message==='AUTH_REQUIRED'?'انتهت الجلسة. سجّل الدخول من جديد.':error.message.startsWith('SPOTIFY_429')?'تم تجاوز حد الطلبات مؤقتًا.':`تعذر البحث: ${error.message.replace('SPOTIFY_','رمز ')}`}}
function runQuickSearch(q){searchInput.value=q;openView('search');searchTracks(q)}
$$('[data-query]').forEach(b=>b.onclick=()=>runQuickSearch(b.dataset.query));
async function loadPlaylists(){playlists.innerHTML='';try{const data=await spotify('/me/playlists?limit=20'),items=data.items||[];playlistStat.textContent=items.length;items.forEach(item=>{const a=document.createElement('a');a.className='playlist-card';a.href=item.external_urls?.spotify||`https://open.spotify.com/playlist/${item.id}`;a.target='_blank';a.rel='noopener';a.innerHTML=`<img src="${item.images?.[0]?.url||''}" alt=""><div><strong></strong><span></span></div>`;a.querySelector('strong').textContent=item.name;a.querySelector('span').textContent=`${item.items?.total??item.tracks?.total??0} أغنية`;playlists.appendChild(a)})}catch{playlistStat.textContent='—';playlists.innerHTML='<p class="muted">تعذر تحديث القوائم الآن.</p>'}}

playPauseButton.onclick=togglePlayback;previousButton.onclick=()=>spotifyPlayer?.previousTrack();nextButton.onclick=()=>spotifyPlayer?.nextTrack();openNowPlaying.onclick=openNowPlayingScreen;openNowPlayingMeta.onclick=openNowPlayingScreen;closeNowPlaying.onclick=closeNowPlayingScreen;nowPlayPause.onclick=togglePlayback;nowPrevious.onclick=()=>spotifyPlayer?.previousTrack();nowNext.onclick=()=>spotifyPlayer?.nextTrack();nowSave.onclick=()=>toggleFavorite(currentTrack);nowFavoriteButton.onclick=()=>toggleFavorite(currentTrack);nowSeek.oninput=()=>{const p=Number(nowSeek.value)/1000;currentPosition=currentDuration*p;renderPlayer()};nowSeek.onchange=()=>spotifyPlayer?.seek(currentPosition);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeNowPlayingScreen()});
authButton.onclick=login;logoutButton.onclick=()=>{spotifyPlayer?.disconnect();clearTokens();location.reload()};searchForm.onsubmit=e=>{e.preventDefault();const q=searchInput.value.trim();if(q)searchTracks(q)};refreshPlaylists.onclick=loadPlaylists;clearHistory.onclick=()=>{searchHistory=[];localStorage.removeItem('asiri_search_history');renderHistory();updateStats()};
renderHistory();renderFavorites();updateStats();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});loadProfile();