const DM_CLIENT_ID='3ac122f971744e508bfd33ad0637d421';
const DM_TASTE_KEY='asiri_taste_profile_v1';
const dm$=s=>document.querySelector(s);
let dmTimer=null;

async function dmRefreshToken(){const rt=localStorage.getItem('spotify_refresh_token');if(!rt)return null;const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:DM_CLIENT_ID,grant_type:'refresh_token',refresh_token:rt})});if(!r.ok)return null;const p=await r.json();localStorage.setItem('spotify_access_token',p.access_token);localStorage.setItem('spotify_expires_at',String(Date.now()+p.expires_in*1000-60000));if(p.refresh_token)localStorage.setItem('spotify_refresh_token',p.refresh_token);return p.access_token}
async function dmToken(){const t=localStorage.getItem('spotify_access_token'),e=Number(localStorage.getItem('spotify_expires_at')||0);return t&&Date.now()<e?t:dmRefreshToken()}
async function dmApi(path,options={}){const t=await dmToken();if(!t)throw new Error('AUTH_REQUIRED');const r=await fetch(`https://api.spotify.com/v1${path}`,{...options,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(`SPOTIFY_${r.status}`);return r.status===204?null:r.json()}
function dmLoadTaste(){try{return JSON.parse(localStorage.getItem(DM_TASTE_KEY)||'{"tracks":{},"artists":{},"events":[]}')}catch{return{tracks:{},artists:{},events:[]}}}
function dmSaveTaste(data){localStorage.setItem(DM_TASTE_KEY,JSON.stringify(data));window.dispatchEvent(new Event('storage'))}
function dmRecord(track,value){if(!track?.id)return;const data=dmLoadTaste(),old=data.tracks[track.id]?.value||'';const artists=(track.artists||[]).map(a=>a.name).filter(Boolean);const adjust=(name,type,delta)=>{const a=data.artists[name]||{likes:0,dislikes:0,score:0};if(type==='like')a.likes=Math.max(0,a.likes+delta);else a.dislikes=Math.max(0,a.dislikes+delta);a.score+=type==='like'?2*delta:-2*delta;data.artists[name]=a};if(old)artists.forEach(n=>adjust(n,old,-1));artists.forEach(n=>adjust(n,value,1));data.tracks[track.id]={id:track.id,name:track.name,artist:artists.join('، '),album:track.album?.name||'',cover:track.album?.images?.[0]?.url||'',url:track.external_urls?.spotify||'',value,updatedAt:Date.now()};data.events.unshift({type:value,trackId:track.id,artist:artists.join('، '),at:Date.now()});data.events=data.events.slice(0,300);dmSaveTaste(data);dm$('#dmStatus').textContent=value==='like'?'تم تسجيل إعجابك ✓':'لن أقترحها مجددًا ✓'}
function dmInject(){if(dm$('#driverMode'))return;const button=document.createElement('button');button.id='driverModeButton';button.className='driver-mode-launch';button.textContent='🚗 وضع السيارة';(dm$('.topbar')||document.body).appendChild(button);const panel=document.createElement('section');panel.id='driverMode';panel.className='driver-mode hidden';panel.innerHTML=`<div class="dm-bg" id="dmBg"></div><div class="dm-content"><header><button id="dmClose">✕</button><div><span>Asiri Music</span><strong>وضع السيارة</strong></div><span class="dm-road">DRIVE</span></header><div class="dm-art"><img id="dmCover" alt="غلاف الأغنية"></div><div class="dm-meta"><h2 id="dmTrack">اختر أغنية للتشغيل</h2><p id="dmArtist">Asiri Music Player</p></div><div class="dm-controls"><button id="dmPrev">⏮</button><button id="dmPlay" class="dm-main">▶</button><button id="dmNext">⏭</button></div><div class="dm-feedback"><button id="dmLike">👍 أعجبتني</button><button id="dmDislike">🚫 لا تقترحها</button></div><div class="dm-moods"><button data-dm-prompt="أبغى أغاني عربية حماسية للسيارة">⚡ حماس</button><button data-dm-prompt="شغل لي جلسة قهوة خليجية هادئة">🌙 هدوء</button><button data-dm-prompt="شغل لي طرب محمد عبده وعبادي الجوهر">🎻 طرب</button><button data-dm-prompt="محمد عبده">محمد عبده</button></div><p id="dmStatus">جاهز للطريق</p></div>`;document.body.appendChild(panel);button.onclick=dmOpen;dm$('#dmClose').onclick=dmClose;dm$('#dmPrev').onclick=()=>dmApi('/me/player/previous',{method:'POST'}).then(()=>setTimeout(dmRefresh,500)).catch(dmError);dm$('#dmNext').onclick=()=>dmApi('/me/player/next',{method:'POST'}).then(()=>setTimeout(dmRefresh,500)).catch(dmError);dm$('#dmPlay').onclick=dmToggle;dm$('#dmLike').onclick=async()=>{const p=await dmCurrent();dmRecord(p?.item,'like')};dm$('#dmDislike').onclick=async()=>{const p=await dmCurrent();dmRecord(p?.item,'dislike');await dmApi('/me/player/next',{method:'POST'});setTimeout(dmRefresh,500)};document.querySelectorAll('[data-dm-prompt]').forEach(b=>b.onclick=()=>dmLaunchSession(b.dataset.dmPrompt))}
async function dmCurrent(){try{return await dmApi('/me/player')}catch{return null}}
async function dmRefresh(){const p=await dmCurrent();if(!p?.item){dm$('#dmStatus').textContent='شغّل أي أغنية أولًا';return}const t=p.item,img=t.album?.images?.[0]?.url||'';dm$('#dmCover').src=img;dm$('#dmTrack').textContent=t.name||'أغنية';dm$('#dmArtist').textContent=t.artists?.map(a=>a.name).join('، ')||'';dm$('#dmPlay').textContent=p.is_playing?'⏸':'▶';dm$('#dmStatus').textContent=p.is_playing?'يعمل الآن':'متوقف مؤقتًا';dm$('#dmBg').style.backgroundImage=img?`linear-gradient(180deg,rgba(3,7,4,.3),rgba(3,7,4,.96)),url("${img}")`:''}
async function dmToggle(){try{const p=await dmCurrent();await dmApi(p?.is_playing?'/me/player/pause':'/me/player/play',{method:'PUT'});setTimeout(dmRefresh,400)}catch(e){dmError(e)}}
function dmOpen(){dm$('#driverMode').classList.remove('hidden');document.body.classList.add('driver-active');dmRefresh();clearInterval(dmTimer);dmTimer=setInterval(dmRefresh,3000)}
function dmClose(){dm$('#driverMode').classList.add('hidden');document.body.classList.remove('driver-active');clearInterval(dmTimer)}
function dmError(e){console.error(e);dm$('#dmStatus').textContent=e?.message==='AUTH_REQUIRED'?'سجّل الدخول مجددًا':'تعذر تنفيذ الأمر الآن'}
function dmLaunchSession(prompt){dmClose();const input=dm$('#aiDjInput'),form=dm$('#aiDjForm');if(input&&form){input.value=prompt;document.querySelector('.tab[data-view="home"]')?.click();setTimeout(()=>form.requestSubmit(),150)}}
const dmStyle=document.createElement('style');dmStyle.textContent=`.driver-mode-launch{border:0;border-radius:999px;background:#1ed760;color:#061009;padding:12px 16px;font-weight:950;cursor:pointer;margin-inline-start:10px}.driver-mode{position:fixed;inset:0;z-index:10000;background:#030604;color:#fff;overflow:auto}.driver-mode.hidden{display:none}.dm-bg{position:absolute;inset:0;background-size:cover;background-position:center;filter:blur(30px) saturate(1.2);transform:scale(1.15);opacity:.42}.dm-content{position:relative;min-height:100%;display:flex;flex-direction:column;align-items:center;padding:max(18px,env(safe-area-inset-top)) 22px max(28px,env(safe-area-inset-bottom))}.dm-content header{width:100%;display:flex;align-items:center;justify-content:space-between}.dm-content header button{width:54px;height:54px;border-radius:50%;border:1px solid #455047;background:#111713;color:#fff;font-size:22px}.dm-content header div{text-align:center}.dm-content header span{display:block;color:#99a49c;font-size:12px}.dm-content header strong{font-size:25px}.dm-road{background:#1ed760!important;color:#051007!important;padding:8px 10px;border-radius:999px;font-weight:950}.dm-art{width:min(68vw,360px);aspect-ratio:1;margin-top:28px}.dm-art img{width:100%;height:100%;object-fit:cover;border-radius:32px;background:#202521;box-shadow:0 28px 80px rgba(0,0,0,.48)}.dm-meta{text-align:center;margin-top:22px;max-width:92vw}.dm-meta h2{font-size:clamp(28px,7vw,48px);line-height:1.2}.dm-meta p{font-size:20px;color:#b7c0b9;margin-top:8px}.dm-controls{display:grid;grid-template-columns:1fr 1.35fr 1fr;gap:18px;width:min(92vw,560px);margin-top:28px}.dm-controls button{min-height:90px;border:0;border-radius:30px;background:#18201a;color:#fff;font-size:38px}.dm-controls .dm-main{background:#1ed760;color:#061009;font-size:48px}.dm-feedback,.dm-moods{display:grid;grid-template-columns:1fr 1fr;gap:12px;width:min(92vw,560px);margin-top:18px}.dm-feedback button,.dm-moods button{min-height:66px;border-radius:22px;border:1px solid #3a443c;background:#121713;color:#fff;font-size:18px;font-weight:850}.dm-feedback button:first-child{border-color:#1ed760}.dm-feedback button:last-child{border-color:#ff7676}.dm-moods{grid-template-columns:repeat(2,1fr)}#dmStatus{margin-top:18px;color:#aab4ac;font-size:16px}.driver-active{overflow:hidden}@media(min-width:780px){.dm-content{justify-content:center}.dm-art{width:300px}.dm-controls button{min-height:78px}}`;document.head.appendChild(dmStyle);dmInject();