const $=s=>document.querySelector(s);
const results=$('#results'),resultCount=$('#resultCount'),searchInput=$('#searchInput'),searchLimitNote=$('#searchLimitNote'),trackTemplate=$('#trackTemplate'),sentinel=$('#searchSentinel');
const PAGE_SIZE=10;
let activeQuery='',currentQuery='',nextOffset=0,loading=false,hasMore=false,searchGeneration=0,lastObservedCount=0;
let seenTrackIds=new Set(),queryQueue=[];

async function refreshToken(){const refreshToken=localStorage.getItem('spotify_refresh_token');if(!refreshToken)return null;const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:'3ac122f971744e508bfd33ad0637d421',grant_type:'refresh_token',refresh_token:refreshToken})});if(!r.ok)return null;const p=await r.json();localStorage.setItem('spotify_access_token',p.access_token);localStorage.setItem('spotify_expires_at',String(Date.now()+p.expires_in*1000-60000));if(p.refresh_token)localStorage.setItem('spotify_refresh_token',p.refresh_token);return p.access_token}
async function token(){const t=localStorage.getItem('spotify_access_token'),e=Number(localStorage.getItem('spotify_expires_at')||0);return t&&Date.now()<e?t:refreshToken()}
async function api(path,options={}){const t=await token();if(!t)throw new Error('AUTH_REQUIRED');const r=await fetch(`https://api.spotify.com/v1${path}`,{...options,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(`SPOTIFY_${r.status}`);return r.status===204?null:r.json()}
function favorites(){return JSON.parse(localStorage.getItem('asiri_favorites')||'[]')}
function updateFavoriteStats(items){const a=$('#favoriteStat'),b=$('#favoriteCount');if(a)a.textContent=items.length;if(b)b.textContent=items.length?`${items.length} أغنية`:''}
function toggleFavorite(track,button){const items=favorites(),i=items.findIndex(x=>x.id===track.id);if(i>=0)items.splice(i,1);else items.unshift({id:track.id,name:track.name,uri:track.uri,artists:track.artists,album:track.album,external_urls:track.external_urls});localStorage.setItem('asiri_favorites',JSON.stringify(items));const active=items.some(x=>x.id===track.id);button.classList.toggle('active',active);button.textContent=active?'♥ ضمن مفضلتي':'♡ مفضلة Asiri';updateFavoriteStats(items)}
async function playTrack(track,button){const original=button.textContent;button.disabled=true;button.textContent='جارٍ التشغيل...';try{const devices=await api('/me/player/devices'),device=devices.devices?.find(x=>x.name==='Asiri Music Player')||devices.devices?.find(x=>x.is_active);if(!device)throw new Error('NO_DEVICE');await api(`/me/player/play?device_id=${encodeURIComponent(device.id)}`,{method:'PUT',body:JSON.stringify({uris:[track.uri||`spotify:track:${track.id}`]})});button.textContent='يعمل الآن ✓'}catch{button.textContent='تعذر التشغيل'}finally{setTimeout(()=>{button.disabled=false;button.textContent=original},1600)}}
function createCard(track){const node=trackTemplate.content.cloneNode(true),fav=node.querySelector('.favorite-track'),active=favorites().some(x=>x.id===track.id);node.querySelector('.track-cover').src=track.album?.images?.[0]?.url||'';node.querySelector('.track-name').textContent=track.name||'بدون اسم';node.querySelector('.track-artist').textContent=track.artists?.map(x=>x.name).join('، ')||'';node.querySelector('.track-album').textContent=track.album?.name||'';node.querySelector('.open-spotify').href=track.external_urls?.spotify||`https://open.spotify.com/track/${track.id}`;node.querySelector('.play-track').onclick=e=>playTrack(track,e.currentTarget);fav.classList.toggle('active',active);fav.textContent=active?'♥ ضمن مفضلتي':'♡ مفضلة Asiri';fav.onclick=()=>toggleFavorite(track,fav);node.querySelector('.save-track').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await api('/me/library',{method:'PUT',body:JSON.stringify({uris:[track.uri||`spotify:track:${track.id}`]})});b.textContent='تم الحفظ ✓'}catch{b.textContent='تعذر الحفظ'}finally{b.disabled=false}};return node}
function setNote(text='',state=''){if(!searchLimitNote)return;searchLimitNote.textContent=text;searchLimitNote.dataset.state=state;searchLimitNote.classList.toggle('hidden',!text)}
function syncCount(){const count=results?.children.length||0;if(resultCount)resultCount.textContent=count?`${count} نتيجة`:''}
function buildQueryQueue(q){const clean=q.replace(/[،,\-–—|]+/g,' ').replace(/\s+/g,' ').trim(),words=clean.split(' ').filter(w=>w.length>1),variants=[];const add=v=>{v=v.trim();if(v&&v!==q&&!variants.includes(v))variants.push(v)};add(clean);if(words.length>2)add(words.slice(0,Math.ceil(words.length/2)).join(' '));if(words.length>1)add(words.slice(-2).join(' '));words.forEach(w=>add(w));add(`${clean} عربي`);add(`${clean} خليجي`);add(`${clean} اغاني`);return variants.slice(0,12)}
function captureInitialResults(query){activeQuery=query;currentQuery=query;queryQueue=buildQueryQueue(query);seenTrackIds=new Set();results.querySelectorAll('.open-spotify').forEach(link=>{const m=link.href.match(/track\/([^?/#]+)/);if(m)seenTrackIds.add(m[1])});nextOffset=Math.max(results.children.length,10);hasMore=results.children.length>0;lastObservedCount=results.children.length;searchGeneration+=1;setNote('مرّر للأسفل لتحميل نتائج إضافية تلقائيًا.','ready');syncCount()}
function moveToNextQuery(){const next=queryQueue.shift();if(!next)return false;currentQuery=next;nextOffset=0;hasMore=true;return true}
async function loadMore(){if(loading||!hasMore||!activeQuery||!results)return;const generation=searchGeneration;loading=true;setNote('جارٍ تحميل نتائج إضافية…','loading');try{let appendedTotal=0,attempts=0;while(appendedTotal===0&&attempts<4&&hasMore){attempts+=1;const params=new URLSearchParams({q:currentQuery,type:'track',limit:String(PAGE_SIZE),offset:String(nextOffset)}),data=await api(`/search?${params}`);if(generation!==searchGeneration)return;const page=data.tracks,items=page?.items||[];items.forEach(track=>{if(!track?.id||seenTrackIds.has(track.id))return;seenTrackIds.add(track.id);results.appendChild(createCard(track));appendedTotal+=1});nextOffset+=items.length;const currentHasMore=Boolean(page?.next)&&items.length>0;if(!currentHasMore&&!moveToNextQuery())hasMore=false;else if(currentHasMore)hasMore=true}
syncCount();if(hasMore)setNote(appendedTotal?'استمر بالنزول لعرض المزيد.':'جارٍ توسيع نطاق البحث…','ready');else setNote('تم عرض جميع النتائج المتاحة والنتائج القريبة من بحثك.','complete')}catch(error){console.error(error);setNote(error.message==='SPOTIFY_429'?'تم بلوغ حد الطلبات مؤقتًا. انتظر قليلًا ثم حرّك الصفحة.':'تعذر تحميل المزيد الآن. حرّك الصفحة قليلًا للمحاولة مجددًا.','error')}finally{loading=false}}
const sentinelObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))loadMore()},{root:null,rootMargin:'800px 0px',threshold:.01});if(sentinel)sentinelObserver.observe(sentinel);
const resultsObserver=new MutationObserver(()=>{const query=searchInput?.value.trim()||'',count=results.children.length;if(!query||count===0){if(count===0){activeQuery=query;currentQuery=query;hasMore=false;nextOffset=0;seenTrackIds.clear();queryQueue=[];lastObservedCount=0;setNote('');syncCount()}return}const fresh=query!==activeQuery||count<lastObservedCount||(lastObservedCount===0&&count>0);if(fresh)captureInitialResults(query);else{lastObservedCount=count;syncCount()}});if(results)resultsObserver.observe(results,{childList:true});searchInput?.addEventListener('input',()=>{if(searchInput.value.trim()!==activeQuery)setNote('')});