const SQ_TASTE_KEY='asiri_taste_profile_v1';
const SQ_DAILY_KEY='asiri_smart_queue_daily_v1';
const SQ_CLIENT_ID='3ac122f971744e508bfd33ad0637d421';
const sq$=s=>document.querySelector(s);
let smartQueue=[];

function sqLoadTaste(){try{return JSON.parse(localStorage.getItem(SQ_TASTE_KEY)||'{"tracks":{},"artists":{},"events":[]}')}catch{return{tracks:{},artists:{},events:[]}}}
function sqDayKey(){return new Date().toISOString().slice(0,10)}
async function sqRefreshToken(){const rt=localStorage.getItem('spotify_refresh_token');if(!rt)return null;const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:SQ_CLIENT_ID,grant_type:'refresh_token',refresh_token:rt})});if(!r.ok)return null;const p=await r.json();localStorage.setItem('spotify_access_token',p.access_token);localStorage.setItem('spotify_expires_at',String(Date.now()+p.expires_in*1000-60000));if(p.refresh_token)localStorage.setItem('spotify_refresh_token',p.refresh_token);return p.access_token}
async function sqToken(){const t=localStorage.getItem('spotify_access_token'),e=Number(localStorage.getItem('spotify_expires_at')||0);return t&&Date.now()<e?t:sqRefreshToken()}
async function sqApi(path,options={}){const t=await sqToken();if(!t)throw new Error('AUTH_REQUIRED');const r=await fetch(`https://api.spotify.com/v1${path}`,{...options,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(`SPOTIFY_${r.status}`);return r.status===204?null:r.json()}
function sqTopArtists(taste){return Object.entries(taste.artists||{}).filter(([,v])=>v.score>0).sort((a,b)=>b[1].score-a[1].score).slice(0,5).map(([name])=>name)}
function sqDisliked(taste){return new Set(Object.values(taste.tracks||{}).filter(x=>x.value==='dislike').map(x=>String(x.id)))}
function sqLiked(taste){return Object.values(taste.tracks||{}).filter(x=>x.value==='like')}
function sqNormalizeTrack(t){return{id:t.id,name:t.name,uri:t.uri||`spotify:track:${t.id}`,artists:t.artists||[],album:t.album||{},external_urls:t.external_urls||{spotify:t.url||`https://open.spotify.com/track/${t.id}`}}}
function sqStore(){localStorage.setItem(SQ_DAILY_KEY,JSON.stringify({day:sqDayKey(),tracks:smartQueue,createdAt:Date.now()}))}
function sqRestore(){try{const saved=JSON.parse(localStorage.getItem(SQ_DAILY_KEY)||'null');if(saved?.day===sqDayKey()&&Array.isArray(saved.tracks)){smartQueue=saved.tracks;return true}}catch{}return false}
function sqShuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

function injectSmartQueue(){if(sq$('#smartQueueCard'))return;const home=sq$('#homeView');if(!home)return;const anchor=sq$('#tasteProfile')||home.querySelector('.stats-grid');if(!anchor)return;const section=document.createElement('section');section.id='smartQueueCard';section.className='smart-queue-card';section.innerHTML=`<div class="sq-head"><div><p class="eyebrow">Smart Queue</p><h2>جلسة أحمد الذكية</h2></div><span id="sqBadge">تتجدد يوميًا</span></div><p id="sqMessage" class="muted">نبني قائمة متتابعة من ذوقك الحقيقي.</p><div id="sqArtists" class="sq-artists"></div><div id="sqPreview" class="sq-preview"></div><div class="sq-actions"><button id="sqBuild">✨ إنشاء الجلسة</button><button id="sqPlay">▶ تشغيل الكل</button><button id="sqSave">＋ حفظ في Spotify</button></div><p id="sqStatus" class="sq-status"></p>`;anchor.insertAdjacentElement('afterend',section);sq$('#sqBuild').onclick=()=>buildSmartQueue(true);sq$('#sqPlay').onclick=playSmartQueue;sq$('#sqSave').onclick=saveSmartQueue;if(sqRestore())renderSmartQueue();else renderSmartQueueEmpty()}
function renderSmartQueueEmpty(){const taste=sqLoadTaste(),artists=sqTopArtists(taste);sq$('#sqArtists').innerHTML=artists.length?artists.map(a=>`<span>${a}</span>`).join(''):'<span>قيّم بعض الأغاني أولًا</span>';sq$('#sqPreview').innerHTML='';sq$('#sqMessage').textContent=artists.length?'جاهزون لبناء جلسة يومية من الفنانين الأقرب لذوقك.':'نحتاج إعجاباتك حتى نصنع جلسة تناسبك.';sq$('#sqStatus').textContent=''}
function renderSmartQueue(){if(!sq$('#smartQueueCard'))return;const taste=sqLoadTaste(),artists=sqTopArtists(taste);sq$('#sqArtists').innerHTML=artists.map(a=>`<span>${a}</span>`).join('');sq$('#sqPreview').innerHTML=smartQueue.slice(0,8).map(t=>`<article><img src="${t.album?.images?.[0]?.url||''}" alt=""><strong>${t.name||''}</strong><small>${t.artists?.map(a=>a.name).join('، ')||''}</small></article>`).join('');sq$('#sqMessage').textContent=`تم تجهيز ${smartQueue.length} أغنية مع استبعاد اختيارات «لا تناسبني».`;sq$('#sqStatus').textContent='الجلسة جاهزة.'}
async function buildSmartQueue(force=false){injectSmartQueue();const status=sq$('#sqStatus'),button=sq$('#sqBuild');if(!force&&sqRestore()){renderSmartQueue();return}button.disabled=true;status.textContent='يجمع الأغاني ويوازن التنوع...';try{const taste=sqLoadTaste(),top=sqTopArtists(taste),disliked=sqDisliked(taste),seen=new Set(),collected=[];for(const liked of sqLiked(taste)){if(liked.id&&!disliked.has(String(liked.id))&&!seen.has(String(liked.id))){seen.add(String(liked.id));collected.push(sqNormalizeTrack({id:liked.id,name:liked.name,artists:String(liked.artist||'').split('،').map(name=>({name:name.trim()})).filter(a=>a.name),album:{name:liked.album||'',images:liked.cover?[{url:liked.cover}]:[]},url:liked.url}))}}const queries=top.length?top:["محمد عبده","عبادي الجوهر","رابح صقر","عبدالمجيد عبدالله"];for(const artist of queries){const params=new URLSearchParams({q:`artist:${artist}`,type:'track',limit:'10',offset:'0'});const data=await sqApi(`/search?${params}`);for(const t of data.tracks?.items||[]){if(!t?.id||seen.has(t.id)||disliked.has(t.id))continue;const names=(t.artists||[]).map(a=>a.name);const artistRejected=names.some(name=>(taste.artists?.[name]?.score||0)<0);if(artistRejected)continue;seen.add(t.id);collected.push(sqNormalizeTrack(t))}}smartQueue=sqShuffle(collected).slice(0,30);if(!smartQueue.length)throw new Error('NO_RESULTS');sqStore();renderSmartQueue();status.textContent='اكتملت الجلسة الذكية ✓'}catch(e){console.error(e);status.textContent=e.message==='AUTH_REQUIRED'?'سجّل الدخول إلى Spotify أولًا.':'تعذر إنشاء الجلسة الآن.'}finally{button.disabled=false}}
async function sqDevice(){const data=await sqApi('/me/player/devices');return data.devices?.find(d=>d.name==='Asiri Music Player')||data.devices?.find(d=>d.is_active)||data.devices?.[0]}
async function playSmartQueue(){const status=sq$('#sqStatus'),button=sq$('#sqPlay');if(!smartQueue.length)await buildSmartQueue(true);if(!smartQueue.length)return;button.disabled=true;status.textContent='جارٍ تشغيل الجلسة...';try{const device=await sqDevice();if(!device)throw new Error('NO_DEVICE');await sqApi(`/me/player/play?device_id=${encodeURIComponent(device.id)}`,{method:'PUT',body:JSON.stringify({uris:smartQueue.map(t=>t.uri)})});status.textContent='بدأ تشغيل الجلسة كاملة ✓'}catch(e){console.error(e);status.textContent='شغّل أي أغنية داخل التطبيق مرة واحدة ثم أعد المحاولة.'}finally{button.disabled=false}}
async function saveSmartQueue(){const status=sq$('#sqStatus'),button=sq$('#sqSave');if(!smartQueue.length)await buildSmartQueue(true);if(!smartQueue.length)return;button.disabled=true;status.textContent='جارٍ الحفظ في Spotify...';try{const me=await sqApi('/me');const list=await sqApi(`/users/${encodeURIComponent(me.id)}/playlists`,{method:'POST',body:JSON.stringify({name:`مختارات أحمد اليوم — ${sqDayKey()}`,description:'جلسة يومية ذكية أنشأها Asiri Music من ملف الذوق',public:false})});await sqApi(`/playlists/${list.id}/tracks`,{method:'POST',body:JSON.stringify({uris:smartQueue.map(t=>t.uri)})});status.textContent='تم حفظ الجلسة في Spotify ✓'}catch(e){console.error(e);status.textContent='تعذر الحفظ الآن.'}finally{button.disabled=false}}

const sqStyle=document.createElement('style');sqStyle.textContent=`.smart-queue-card{margin:22px 0;padding:21px;border-radius:26px;border:1px solid rgba(112,132,255,.28);background:linear-gradient(145deg,#171b32,#101317 58%,#102019);box-shadow:0 22px 60px rgba(0,0,0,.25)}.sq-head{display:flex;justify-content:space-between;gap:12px}.sq-head span{height:max-content;padding:7px 10px;border-radius:999px;background:#8fa0ff;color:#080b16;font-size:11px;font-weight:900}.sq-artists{display:flex;gap:7px;overflow:auto;margin-top:12px;scrollbar-width:none}.sq-artists span{flex:0 0 auto;padding:8px 11px;border:1px solid #3b4264;border-radius:999px;font-size:12px}.sq-preview{display:flex;gap:9px;overflow:auto;margin-top:15px;padding-bottom:4px;scrollbar-width:none}.sq-preview article{flex:0 0 104px}.sq-preview img{width:104px;height:104px;border-radius:15px;object-fit:cover;background:#252a26}.sq-preview strong,.sq-preview small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sq-preview strong{font-size:12px;margin-top:7px}.sq-preview small{font-size:10px;color:#99a19b;margin-top:3px}.sq-actions{display:grid;grid-template-columns:1.1fr 1fr 1fr;gap:8px;margin-top:16px}.sq-actions button{border:0;border-radius:999px;padding:12px 10px;font-weight:900;cursor:pointer}.sq-actions button:first-child{background:#8fa0ff;color:#080b16}.sq-actions button:nth-child(2){background:#1ed760;color:#041006}.sq-actions button:nth-child(3){background:#fff;color:#080b0a}.sq-actions button:disabled{opacity:.55}.sq-status{min-height:18px;margin-top:10px;color:#aeb6b0;font-size:12px;text-align:center}@media(max-width:620px){.sq-actions{grid-template-columns:1fr}.smart-queue-card{padding:18px}}`;document.head.appendChild(sqStyle);

injectSmartQueue();
const sqObserver=new MutationObserver(injectSmartQueue);sqObserver.observe(document.body,{childList:true,subtree:true});
window.addEventListener('storage',()=>{renderSmartQueueEmpty();buildSmartQueue(true)});
